name: FactInt
version: 1.6.1
date: 17/01/2018
description: |
    Advanced Methods for Factoring Integers

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk

GAP: ">=4.8.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.6"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/FactInt
readme: README.md
packageinfo: https://gap-packages.github.io/FactInt/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/FactInt/releases/download/v1.6.1/FactInt-1.6.1.tar.gz

abstract: |
    
    This package provides routines for factoring integers, in particular:
    <ul>
      <li>Pollard's <em>p</em>-1</li>
      <li>Williams' <em>p</em>+1</li>
      <li>Elliptic Curves Method (ECM)</li>
      <li>Continued Fraction Algorithm (CFRAC)</li>
      <li>Multiple Polynomial Quadratic Sieve (MPQS)</li>
    </ul>
    It also provides access to Richard P. Brent's tables of factors of integers of the form <em>b</em>^<em>k</em> +/- 1.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
