name: FactInt
version: "1.7.0"
license: "GPL-2.0-or-later"
date: 2026-08-07
description: |
    Advanced Methods for Factoring Integers

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/

GAP: ">=4.10"

www: https://gap-packages.github.io/FactInt
readme: README.md
packageinfo: https://gap-packages.github.io/FactInt/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/FactInt/releases/download/v1.7.0/FactInt-1.7.0.tar.gz

abstract: |
    
    This package provides routines for factoring integers, in particular:
    <ul>
      <li>Pollard's <em>p</em>-1</li>
      <li>Williams' <em>p</em>+1</li>
      <li>Elliptic Curves Method (ECM)</li>
      <li>Continued Fraction Algorithm (CFRAC)</li>
      <li>Multiple Polynomial Quadratic Sieve (MPQS)</li>
    </ul>
    It also provides access to Richard P. Brent's tables of factors of integers of the form <em>b</em>^<em>k</em> +/- 1.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Integer factorization, ECM, Elliptic Curves Method, MPQS, Multiple Polynomial Quadratic Sieve, CFRAC, Continued Fraction Algorithm, Pollard's p-1, Williams' p+1, Cunningham Tables, Richard P. Brent's Factor Tables.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Koh26</span>]   <b class='BibAuthor'>Kohl, S.</b>,
     <i class='BibTitle'>FactInt, Advanced Methods for Factoring Integers,
             Version 1.7.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/FactInt">https://gap-packages.github.io/FactInt</a></span>.
    </p>
    

bibtex: |
    @misc{ FactInt,
      author =           {Kohl, S.},
      title =            {{FactInt},  {Advanced Methods for Factoring Integers},
                          {V}ersion 1.7.0},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/FactInt}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{FactInt}}},
      keywords =         {Integer  factorization;  ECM;  Elliptic Curves Method;
                          MPQS;  Multiple  Polynomial  Quadratic  Sieve;  CFRAC;
                          Continued      Fraction      Algorithm;      Pollard's
                          p\texttt{\symbol{45}}1;   Williams'   p+1;  Cunningham
                          Tables; Richard P. Brent's Factor Tables},
      printedkey =       {Koh26}
    }

